### ISSUE TITLE
Plugin causes the editor to be unable to reload previously opened files after app is roloaded.

### ISSUE THREAD

**Issue by BizzyEL** [7HR4IZ3/acode_plugin_coderunner#3]
After installing the CodeRunner plugin for Acode, everything works as expected but, after exiting and reopening the acode app, the contents of the previously opened files will not be reloaded. Sometimes, I'd have to re-add the folders again in order to have access to the files.

**Expected Behavior**
After exiting the acode app, reopening it should reload the contents of previously opened files & folders (i.e. files & folders that were open when the app was exited).

**Error Encountered**
As long as the coderunner plugin is installed, reopening the acode app after exiting it doesn't reload contents of the files that were open when the app was exited.

**Steps to Reproduce Error**
- Install Acode Editor (for android) and load the app
- Install AcodeX Plugin (if not already installed)
- Install the Code Runner Plugin
- Open a file (or create a new file and save it with some texts).
- Click the 3-vertical-dots at the top-right corner and then click exit to Exit the acode app. Do not close the opened files before exiting.
- Reopen the acode app.

Once done, a new "untitled.txt" file will be created along side the previously opened file, but, it's content will not be loaded.

**Comment by ansarimohammed422** [comment]
I also have encountered this error

**Comment by NIXININE** [comment]
Fixed in the latest release for me.
