### ISSUE TITLE
Cant run c codes

### ISSUE THREAD

**Issue by Rakeshyadav-19** [7HR4IZ3/acode_plugin_coderunner#5]

**Comment by Sickdused** [comment]
![Screenshot_20240219-082809](https://github.com/7HR4IZ3/acode_plugin_coderunner/assets/92903009/9c60070d-4003-492f-9af1-2f544c2392a0)
Mine can't run c/c++ codes. It says permission denied even though I gave permission to the app.
Here is my device information.

![Screenshot_20240219-082816](https://github.com/7HR4IZ3/acode_plugin_coderunner/assets/92903009/eed3d060-0774-4659-9408-03b7eb0be71a)

![Screenshot_20240219-082839](https://github.com/7HR4IZ3/acode_plugin_coderunner/assets/92903009/3f7554ba-30f9-45b4-af4b-000fe43a84f8)


![Screenshot_20240219-082950](https://github.com/7HR4IZ3/acode_plugin_coderunner/assets/92903009/43ce7408-55a7-403f-9b55-5b8edfde7932)

**Comment by Sickdused** [comment]
Mine can't run c/c++ codes. It says permission denied even though I gave permission to the app.

Here are my device specifications: 

![Screenshot_20240219-083652](https://github.com/7HR4IZ3/acode_plugin_coderunner/assets/92903009/e6e2940d-1b55-4df0-8a82-d19d1d0ca91a)
![Screenshot_20240219-082839](https://github.com/7HR4IZ3/acode_plugin_coderunner/assets/92903009/e37c2862-3945-4409-8a1c-da6c775ef024)
![Screenshot_20240219-082809](https://github.com/7HR4IZ3/acode_plugin_coderunner/assets/92903009/7e75e9af-4e1c-42c2-950d-11d2b3a8496d)
![Screenshot_20240219-082816](https://github.com/7HR4IZ3/acode_plugin_coderunner/assets/92903009/22c55911-1097-41f7-b754-b7b8ff423e35)

**Comment by 7HR4IZ3** [comment]
Sorry about the delay, just seeing this issue now😓

It's a problem with Termux not Coderunner
To fix run this first `chmod +x <name_of_executable>` then try again 

Or if you don't want to do it everytime, then find the ones for c and c++ then add this to your `commands.json` file, under the command property just before `./$nameNoExt` add  `chmod +x ./$nameNoExt; `

**Comment by 7HR4IZ3** [comment]
Problem with Android, not Termux, Android dosen't allow running executables in the /sdcard or /storage/emulated/0 folders, move your code to Termux directory, it would work there.

**Comment by 7HR4IZ3** [comment]
Problem with Android, not Termux, Android dosen't allow running executables in the /sdcard or /storage/emulated/0 folders, move your code to Termux directory, it would work there.
